### ISSUE TITLE
Install fails due to error from driver installer: Certificate used to sign package is not trusted. 

### ISSUE THREAD

**Issue by r14n** [Benjamin-Dobell/nvidia-update#12]
Downloading driver blacklist...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    80  100    80    0     0    440      0 --:--:-- --:--:-- --:--:--   439

Downloading driver list...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 55865  100 55865    0     0  73424      0 --:--:-- --:--:-- --:--:-- 73506

The latest driver revision is 378.05.05.25f01

Downloading 378.05.05.25f01 drivers...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 62.1M  100 62.1M    0     0  6087k      0  0:00:10  0:00:10 --:--:-- 6735k

Installing new drivers...
installer: Package name is NVIDIA Web Driver 378.05.05.25f01
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
Richards-iMac:~ r14n$ ./nvidia-update.sh -allowUntrusted
Downloading driver blacklist...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    80  100    80    0     0    764      0 --:--:-- --:--:-- --:--:--   769

Downloading driver list...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 55865  100 55865    0     0  79483      0 --:--:-- --:--:-- --:--:-- 79466

**Comment by Benjamin-Dobell** [comment]
I'm not quite sure why this is needed on your system, it seems unnecessary on the system's I've tested on, but they're all High Sierra. Nonetheless, I've made the change to support unsigned packages. Hopefully everything now works as expected.

**Comment by r14n** [comment]
Thanks.  FWIW after the installer failed I was left driverless and went and
got the regular installer from NVidia.  Even though I downloaded it from
their site and ran in the same minute, their own installer gave me a
warning about the certificate being bad so it could be a problem on their
end, maybe with that particular driver.

Also, I think I was already running that same driver version before running
your script.  Not sure if your script does or tries to check which version
the system is currently running, but might be a nice add as well.

Thanks for your work!

**Comment by Benjamin-Dobell** [comment]
It does, or rather is supposed, to detect if you're already on the latest drivers. I can run it repeatedly and it only downloads when it needs to. However, it's certainly conceivable there's a bug.
