### ISSUE TITLE
Post-install Error: Architecture couldn't be recognized!

### ISSUE THREAD

**Issue by mgoggin** [Benjamin-Dobell/nvidia-update#15]
Thanks for this tool!

I'm having an issue when trying to install the latest non-blacklisted driver on my system. The tool appears to run fine (no errors), but on reboot, I'm stuck with default resolution and no acceleration (hinting that the driver isn't loaded).

When I check my logs, I see the following:

```
(NVDAStartup) Architecture couldn't be recognized! PMC_BOOT_0 = <private>, PMC_BOOT_42 = 0x00000013
```

The latest driver from Nvidia works, but I'm noticing a severe performance degradation. I'm hoping I can get this tool to work and try out a different driver.

Here are my specs:

- macOS High Sierra (10.13.3 17D102)
- Hackintosh (emulated iMac18,3)
- ASUS ROG Maximus X Hero Wi-Fi AC (Z370)
- Intel Core i7-8700K
- 32GB DDR4-3200
- Gigabyte GTX 1080 G1 Gaming
- 3x Dell P2715Q (over DP) at 4K@60

Let me know if there's any more information I can provide or what I can do to help troubleshoot this issue.

**Comment by Benjamin-Dobell** [comment]
May I please suggest posting over at https://www.tonymacx86.com/ instead? As I don't believe this issue is to do with `nvidia-update` itself, but nVidia's drivers not liking your system setup. Personally, I don't know enough about your hardware to be particularly helpful.
