### ISSUE TITLE
Mac OS 10.3.4 Drivers

### ISSUE THREAD

**Issue by MiGzY** [Benjamin-Dobell/nvidia-update#16]
any ideas when NVidia are releasing drivers to support 10.3.4?  I get the following echo.

Could not find a release for your OS.

The latest recommended release is:
 378.10.10.10.25.106

**Comment by icex** [comment]
387.10.10.10.30.103 is released now but not a good driver(at least for me). It feels laggy, no cuda support. I force installed 378.10.10.10.25.106 and works well.

> ./nvidia-update.sh -f 378.10.10.10.25.106

**Comment by stevenliuit** [comment]
this is new cuda version 
but not a good driver
this name：cudadriver_387.178_macos.dmg

**Comment by 0x7fffffff** [comment]
387.10.10.10.30.103 released today and still has problems.

**Comment by stevenliuit** [comment]
Still 378.10.10.10.25.106 this version is not stuck

**Comment by tmikaeld** [comment]
It's amazing how the drivers STILL suck enormously, is Nvidia even aware of the issues?

Now that external GPU is released and anyone use the new drivers, they would get so disappointed.

**Comment by Benjamin-Dobell** [comment]
Marking this issue as closed seems as 387.10.10.10.30.103 has been blacklisted.
