### ISSUE TITLE
Doesn't do the AGDP patch for Black screen

### ISSUE THREAD

**Issue by rhcp011235** [Benjamin-Dobell/nvidia-update#24]
Doesn't do the AGDP patch for Black screen

**Comment by rhcp011235** [comment]
Hey,

I hate to link tonymac but, my buddy who made the 'fix' posted it on here: https://www.tonymacx86.com/threads/black-screen-with-macpro-6-1-or-imac-15-or-imac-17-system-definition.183113/

it's for when you use MacPro 6.1 SMBIOS and a few others. it causes a black screen.

**Comment by rhcp011235** [comment]
its a rather simple patch. I think there are other ways to do it too. would be cool to see it added into this. one click install + patch if needed :)

**Comment by Benjamin-Dobell** [comment]
Sorry, this is out of scope for this project. There are existing solutions and this project is only concerned with installing/running official nVidia drivers at this point.
