### ISSUE TITLE
Better copy/paste script

### ISSUE THREAD

**Issue by shelldandy** [Benjamin-Dobell/nvidia-update#25]
```sh
curl -s https://raw.githubusercontent.com/Benjamin-Dobell/nvidia-update/master/nvidia-update.sh | bash
```

That way even works on fish-shell :v

**Comment by Benjamin-Dobell** [comment]
Unfortunately, this won't work for input. On certain occasions this script prompts for confirmation.

**Comment by Benjamin-Dobell** [comment]
I'm certainly open to suggestions, however this has been brought up before and we couldn't come up with a better solution. So I'll close this for now, but if you can come up with something more portable that supports input as well please let me know.

**Comment by shelldandy** [comment]
gotcha, no problem :)
