### ISSUE TITLE
operation not permitted

### ISSUE THREAD

**Issue by tjmille2** [Benjamin-Dobell/nvidia-update#3]
sudo ./nvidia-update.sh yields file not found

sudo bash ./nvidia-update.sh yield "Operation not permitted"

**Comment by Benjamin-Dobell** [comment]
I would suggest going with the simplest execution:

```
bash <(curl -s https://raw.githubusercontent.com/Benjamin-Dobell/nvidia-update/master/nvidia-update.sh)
```

Otherwise, the issue is that you haven't made the script executable. You'll want to:

```
chmod 755 nvidia-update.sh
```

Also, there's no need to run the script with `sudo`, it'll prompt you for sudo permission if/when required.

**Comment by Benjamin-Dobell** [comment]
Ah, I just realised, my apologies on the `sudo` thing, I need to update the `README`.
