### ISSUE TITLE
how to uninstall?

### ISSUE THREAD

**Issue by JanC** [Benjamin-Dobell/nvidia-update#38]
Hey,
I used the script but only then realised that my RTX 2070 Super is not supported at all by Hackintosh.

What is the easiest way to uninstall the installed drivers by this script?

cheers

**Comment by Benjamin-Dobell** [comment]
Easiest way is to uninstall from the "NVIDIA Driver Manager" in System Preferences. Otherwise you can paste the following in a terminal:

```sh
sudo installer -pkg "/Library/PreferencePanes/NVIDIA Driver Manager.prefPane/Contents/MacOS/NVIDIA Web Driver Uninstaller.app/Contents/Resources/NVUninstall.pkg" -target /
```

In both cases, you're running the official uninstaller.
