### ISSUE TITLE
The install failed

### ISSUE THREAD

**Issue by antonio-leonardo** [Benjamin-Dobell/nvidia-update#41]
**Hi
I'm try to run this script and at the end prompt this message bellow**

> _installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)_

**May you have a solution of this error?
Tks, regards!**

**Comment by b23prodtm** [comment]
It's blocked by pkg file permissions somewhere from TMPDIR in the script. Browse to the Downlads folder :

     cd ~/Downloads
     TMPDIR=`pwd` <(curl -O https://raw.githubusercontent.com/Benjamin-Dobell/nvidia-update/master/nvidia-update.sh)

**Comment by coalfield** [comment]
@b23prodtm I have the same issue, tried the above and the same story :(

```
Installing new drivers...
installer: Package name is NVIDIA Web Driver 387.10.10.10.40.135
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)
```

**Comment by rhawool** [comment]
Even I am facing the same issue. Please address.

`Patched install requirements.
Patched extension.

Repackaging...

Installing new drivers...
installer: Package name is NVIDIA Web Driver 387.10.10.10.40.137
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)`

**Comment by antonio-leonardo** [comment]
> **Hi I'm try to run this script and at the end prompt this message bellow**
> 
> > _installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)_
> 
> **May you have a solution of this error? Tks, regards!**

Hi @Benjamin-Dobell ,

I understood the problem: My macOS scenario was Mojave/Catalina versions installed by [DosDude1 Software](http://dosdude1.com); this installs Mojave/Catalina on Mac Hardware not supported by Apple for Mojave/Catalina; then, I install HighSierra version on my Mac and execute your script and it works.

Sorry to not detailed my question and thanks for script contribute.

**Comment by rhawool** [comment]
> > **Hi I'm try to run this script and at the end prompt this message bellow**
> > > _installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)_
> > 
> > 
> > **May you have a solution of this error? Tks, regards!**
> 
> Hi @Benjamin-Dobell ,
> 
> I understood the problem: My macOS scenario was Mojave/Catalina versions installed by [DosDude1 Software](http://dosdude1.com); this installs Mojave/Catalina on Mac Hardware not supported by Apple for Mojave/Catalina; then, I install HighSierra version on my Mac and execute your script and it works.
> 
> Sorry to not detailed my question and thanks for script contribute.

Hello,

Could you please share the steps you followed.
Thanks

**Comment by antonio-leonardo** [comment]
> > > **Hi I'm try to run this script and at the end prompt this message bellow**
> > > > _installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)_
> > > 
> > > 
> > > **May you have a solution of this error? Tks, regards!**
> > 
> > 
> > Hi @Benjamin-Dobell ,
> > I understood the problem: My macOS scenario was Mojave/Catalina versions installed by [DosDude1 Software](http://dosdude1.com); this installs Mojave/Catalina on Mac Hardware not supported by Apple for Mojave/Catalina; then, I install HighSierra version on my Mac and execute your script and it works.
> > Sorry to not detailed my question and thanks for script contribute.
> 
> Hello,
> 
> Could you please share the steps you followed.
> Thanks

Sure!
I'll use some article references to more detail the steps:

1-I make a usb-flash macOS High Sierra bootable drive, following [Apple Support](https://support.apple.com/en-us/HT201372)
2-I start my MacBook 2009 from this prepared Usb Bootable Drive, choiced by "Opt"+"Command";
3-And starts a clean install, with similar step like this article [How to clean install macOS Catalina and older versions](https://www.macworld.co.uk/how-to/mac-software/clean-install-macos-3637409/);
4-macOS High Sierra is compatible with my MacBook 2009 hardware; then, after 1,2,3 steps, I execute @Benjamin-Dobell 's script instructions and it was successful to install my NVIDIA driver update;

**Comment by rhawool** [comment]
> > > > **Hi I'm try to run this script and at the end prompt this message bellow**
> > > > > _installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)_
> > > > 
> > > > 
> > > > **May you have a solution of this error? Tks, regards!**
> > > 
> > > 
> > > Hi @Benjamin-Dobell ,
> > > I understood the problem: My macOS scenario was Mojave/Catalina versions installed by [DosDude1 Software](http://dosdude1.com); this installs Mojave/Catalina on Mac Hardware not supported by Apple for Mojave/Catalina; then, I install HighSierra version on my Mac and execute your script and it works.
> > > Sorry to not detailed my question and thanks for script contribute.
> > 
> > 
> > Hello,
> > Could you please share the steps you followed.
> > Thanks
> 
> Sure!
> I'll use some article references to more detail the steps:
> 
> 1-I make a usb-flash macOS High Sierra bootable drive, following [Apple Support](https://support.apple.com/en-us/HT201372)
> 2-I start my MacBook 2009 from this prepared Usb Bootable Drive, choiced by "Opt"+"Command";
> 3-And starts a clean install, with similar step like this article [How to clean install macOS Catalina and older versions](https://www.macworld.co.uk/how-to/mac-software/clean-install-macos-3637409/);
> 4-macOS High Sierra is compatible with my MacBook 2009 hardware; then, after 1,2,3 steps, I execute @Benjamin-Dobell 's script instructions and it was successful to install my NVIDIA driver update;

thanks!

**Comment by antonio-leonardo** [comment]
> > > > > **Hi I'm try to run this script and at the end prompt this message bellow**
> > > > > > _installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)_
> > > > > 
> > > > > 
> > > > > **May you have a solution of this error? Tks, regards!**
> > > > 
> > > > 
> > > > Hi @Benjamin-Dobell ,
> > > > I understood the problem: My macOS scenario was Mojave/Catalina versions installed by [DosDude1 Software](http://dosdude1.com); this installs Mojave/Catalina on Mac Hardware not supported by Apple for Mojave/Catalina; then, I install HighSierra version on my Mac and execute your script and it works.
> > > > Sorry to not detailed my question and thanks for script contribute.
> > > 
> > > 
> > > Hello,
> > > Could you please share the steps you followed.
> > > Thanks
> > 
> > 
> > Sure!
> > I'll use some article references to more detail the steps:
> > 1-I make a usb-flash macOS High Sierra bootable drive, following [Apple Support](https://support.apple.com/en-us/HT201372)
> > 2-I start my MacBook 2009 from this prepared Usb Bootable Drive, choiced by "Opt"+"Command";
> > 3-And starts a clean install, with similar step like this article [How to clean install macOS Catalina and older versions](https://www.macworld.co.uk/how-to/mac-software/clean-install-macos-3637409/);
> > 4-macOS High Sierra is compatible with my MacBook 2009 hardware; then, after 1,2,3 steps, I execute @Benjamin-Dobell 's script instructions and it was successful to install my NVIDIA driver update;
> 
> thanks!

You're welcome!

**Comment by antonio-leonardo** [comment]
It's can be consider closed, thanks a lot for attention on this topic.
