### ISSUE TITLE
NVIDIAEGPUSupport.kext necessary?

### ISSUE THREAD

**Issue by anonymouz4** [Benjamin-Dobell/nvidia-update#7]
With this script, is it still necessary to install NVIDIAEGPUSupport.kext from [Github Link](https://github.com/pedroresende/NVIDIAEGPUSupport)? Users in the [EGPU.IO Forum](https://egpu.io/forums/mac-setup/wip-nvidia-egpu-support-for-high-sierra) were not sure so I'm asking.

**Comment by Benjamin-Dobell** [comment]
Yes, it is still necessary.

I'm _considering_ adding eGPU support, however the primary purpose of this script is just to install the latest _reliable_ nVidia web drivers. I'll certainly update the egpu.io if I do add specific eGPU support.
