### ISSUE TITLE
suggested installed method is unsafe and not portable

### ISSUE THREAD

**Issue by ickc** [Benjamin-Dobell/nvidia-update#9]
> `bash <(curl -s https://raw.githubusercontent.com/Benjamin-Dobell/nvidia-update/master/nvidia-update.sh)`

This has a few problems:

1. assume the shell is bash (`<(...)` syntax): can be fixed by using standard curl bash piping syntax
2. the script isn't written in a way that prevent half downloaded script to run (the standard practice to do this is to put the whole script in a function, so that if not loaded fully, it will simply resulted in a syntax error and not run at all)

**Comment by Benjamin-Dobell** [comment]
> 1. assume the shell is bash (<(...) syntax): can be fixed by using standard curl bash piping syntax

Well, it's a bash script, so it's a bit of an assumption that it'll run in other shells ;) It probably won't.

I use zsh as my primary shell, nonetheless this script is a bash script. See that the script's shebang is:

```
#!/bin/sh
```

which is bash on macOS (and not user configurable):

```
$ /bin/sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
```

> 2. the script isn't written in a way that prevent half downloaded script to run

Good catch, I'll rectify this. Thanks 👍

**Comment by Benjamin-Dobell** [comment]
Ah sorry, I misinterpreted your first point. You can't pipe a script to a shell if the script requires user input. This script does under certain circumstances, this is why `<( ... )` syntax is suggested.

**Comment by Benjamin-Dobell** [comment]
It's probably worth noting that process substitution (`<( ... )`) is supported by both [bash](https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html#Process-Substitution) and [zsh](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Process-Substitution).

The former is likely to cover something like 90% of users with the latter covering a further 9.99% 
>  **Note:** _Provided percentages are entirely made-up_ 😉

If you're using a different shell, like `fish` for example, then you probably know what you're getting yourself into.

**Comment by ickc** [comment]
Well, you're quick. I made other changes and see if you want to merge them. I can rebase later if you want.

**Comment by ickc** [comment]
> The former is likely to cover something like 90% of users with the latter covering a further 9.99%

That's not true...

And the point of providing a 1-liner is such that anyone can copy and paste that line to expect it works. To assume people using other default shell to rewrite your 1-liner will not be a very good user experience. And syntactically I don't see why a pipe is inferior than `<(...)` in this case since it is so simple either way. (For more complex scripts I see why and do use the `<(...)` syntax especially when it is protected by a shebang so I know what shell it is going to be run in.)

**Comment by ickc** [comment]
> You can't pipe a script to a shell if the script requires user input. This script does under certain circumstances, this is why <( ... ) syntax is suggested.

Oh, sorry, I missed this point. Ok, so no solution other than using `<(...)` then? I'll revoke that commit then.

**Comment by ickc** [comment]
How about

```bash
curl -s https://raw.githubusercontent.com/Benjamin-Dobell/nvidia-update/master/nvidia-update.sh | bash -
```

This may be supported by more shell than `<(...)`.

**Comment by Benjamin-Dobell** [comment]
I responded in your PR, but will leave my response here as well, just in case someone else stumbles across this issue...

> Unfortunately pipe syntax just won't work no matter how you do it (to my knowledge).
> 
> To test, put the following in `test.sh`:
> 
> ```
> #!/bin/sh
>   
> printf "\n"
> read -p "Do you want to reply yes? [Y/n] " -n 1 -r
> printf "\n"
> 
> if [[ $REPLY =~ ^[Yy]$ ]]; then
>         echo "You replied yes."
> else
>         echo "Not yes"
> fi
> ```
> 
> Then execute it with:
> 
> ```
> cat test.sh | bash -
> ```
> 
> It errors with:
> 
> ```
> bash: line 5: rintf: command not found
> ```
> 
> I'm all for portability, unfortunately I think the current solution (bash and zsh support) is the best we can do.
